### ISSUE TITLE
AttributeError: module 'importlib.resources' has no attribute 'files'

### ISSUE THREAD

**Issue by GhostFlagged** [shriyanss/subdomain_wordlist_gen#7]
Hi, i when i want to use your program i get error like this i use the setup.py file also using pip and i have same error 
```
Traceback (most recent call last):
  File "/usr/local/bin/subgen", line 11, in <module>
    load_entry_point('subgen==0.0.1', 'console_scripts', 'subgen')()
  File "/usr/local/lib/python3.8/dist-packages/subgen-0.0.1-py3.8.egg/subgen/subgen/cli.py", line 29, in main
  File "/usr/local/lib/python3.8/dist-packages/subgen-0.0.1-py3.8.egg/subgen/subgen/cli.py", line 7, in banner
  File "/usr/local/lib/python3.8/dist-packages/pyfiglet-1.0.2-py3.8.egg/pyfiglet/__init__.py", line 67, in figlet_format
    fig = Figlet(font, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pyfiglet-1.0.2-py3.8.egg/pyfiglet/__init__.py", line 862, in __init__
    self.setFont()
  File "/usr/local/lib/python3.8/dist-packages/pyfiglet-1.0.2-py3.8.egg/pyfiglet/__init__.py", line 869, in setFont
    self.Font = FigletFont(font=self.font)
  File "/usr/local/lib/python3.8/dist-packages/pyfiglet-1.0.2-py3.8.egg/pyfiglet/__init__.py", line 128, in __init__
    self.data = self.preloadFont(font)
  File "/usr/local/lib/python3.8/dist-packages/pyfiglet-1.0.2-py3.8.egg/pyfiglet/__init__.py", line 141, in preloadFont
    path = importlib.resources.files('pyfiglet.fonts').joinpath(fn)
AttributeError: module 'importlib.resources' has no attribute 'files'```

**Comment by shriyanss** [comment]
Hi there,
Can you please try `pip install --upgrade pyfiglet`

As a temporary solution, you might add `-s` flag so the responsible function won't be called.

If the above command doesn't work, please let me know the following:-
- Operating system
- Python version
- Pyfiglet version (`pip show pyfiglet`)

Regards
@shriyanss

**Comment by GhostFlagged** [comment]
hi using the subgen -s -i wordlist.txt will work

Os :
```
ubuntu
```
Python version:
```
Python 3.8.10
```

Pyfiglet version : 

```Name: pyfiglet
Version: 1.0.2
Summary: Pure-python FIGlet implementation
Home-page: https://github.com/pwaller/pyfiglet
Author: Peter Waller (Thanks to Christopher Jones and Stefano Rivera)
Author-email: p@pwaller.net
License: MIT
Location: /usr/local/lib/python3.8/dist-packages/pyfiglet-1.0.2-py3.8.egg
Requires: 
Required-by: subgen```

**Comment by shriyanss** [comment]
Hi @Abracadabra0x,
Thanks for providing this info.

As per the GitHub repo for the library used, it states:-
> The latest pyfiglet version requires python >= 3.9

(see https://github.com/pwaller/pyfiglet/issues/132)

So upgrading the python version will help.

Also, the feature causing the issue is the function printing the banner, so using the `-s`/`--silent` flag will not print the banner.

Regards
@shriyanss
